=== mikafouenski/Projet-XML/master.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT master (ue+, intervenant+, parcours+)>

<!ELEMENT ue (nom, credit, vol_horaire, description, plan, lieu, ref-intervenant+)>
<!ATTLIST ue id ID #IMPLIED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT vol_horaire (#PCDATA)>
<!ELEMENT plan (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT ref-intervenant EMPTY>
<!ATTLIST ref-intervenant ref IDREF #IMPLIED>

<!ELEMENT intervenant (nom, prenom, mail, site, ref-ue*)>
<!ATTLIST intervenant id ID #IMPLIED>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT site (#PCDATA)>
<!ELEMENT ref-ue EMPTY>
<!ATTLIST ref-ue ref IDREF #IMPLIED>

<!ELEMENT parcours (ref-intervenant+, nom, description, debouche*, semestre+)>
<!ELEMENT debouche (#PCDATA)>
<!ELEMENT semestre ((ref-ue, role)+)>
<!ELEMENT role EMPTY>
<!ATTLIST role obligatoire (F|V) #REQUIRED>

<!ELEMENT description (p | ul)*>
<!ELEMENT p (#PCDATA | b | i | a | u)*>
<!ELEMENT ul (li*)>
<!ELEMENT li (t | b | u | i | br | p)*>

<!ELEMENT b (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT a (#PCDATA)>
<!ELEMENT t (#PCDATA)>
<!ELEMENT u (#PCDATA)>
<!ELEMENT br EMPTY>

=== mikafouenski/Projet-XML/master/master.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE master
  SYSTEM "master.dtd">
<master>
   <ue id="ENSINAU1">
      <nom>Génie Logiciel</nom>
      <credit>6</credit>
      <vol_horaire>60</vol_horaire>
      <description>
         <p>
            <t>- Processus logiciel</t>
            <br/>
            <t>- Gestion de projet</t>
            <br/>
            <t>- Spécification et conception (artefact : notation UML)</t>
            <br/>
            <t>- Design patterns</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
      <ref-intervenant ref="IN7722"/>
   </ue>
   <ue id="ENSINAU10">
      <nom>Modèles à évènements discrets</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>Posséder les notions de base en modélisation et analyse de systèmes dynamiques à événements discrets et particulièrement appréhender le formalisme réseau de</t>
            <br/>
            <t>Pétri. Étudier la conception et la spécification des systèmes réactifs à travers l'analyse du modèle à évènements discrets (concurrence, parallélisme, synchronisation).</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINAU11">
      <nom>Introduction à l'apprentissage automatique</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>- Introduction aux concepts de bases : formalisme statistique, erreur de généralisation</t>
            <br/>
            <t>- Arbres de décision : algorithme ID3, élagage, programmation</t>
            <br/>
            <t>- Algorithme du perceptron : algorithme, temps de convergence, propriétés de généralisation, application à la classification de textes</t>
            <br/>
            <t>- Régression logistique : cadre probabiliste, maximisation de la vraisemblance, optimisation par gradient conjugué et méthode de Newton, application à la classification de textes</t>
            <br/>
            <t>- Quelques éléments théoriques : notion de capacité de classes de fonctions, complexité de Rademacher, borne dépendante des données.</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINAU2">
      <nom>Complexité</nom>
      <credit>6</credit>
      <vol_horaire>60</vol_horaire>
      <description>
         <p>
            <t>- Rappels sur les notions d'analyse de la complexité des algorithmes et des problèmes.</t>
            <br/>
            <t>- Notion de problèmes (décision, recherche, dénombrement, énumération, optimisation). Bornes inférieures de complexité.</t>
            <br/>
            <t>- Classes P et NP. Problèmes NP-complets.</t>
            <br/>
            <t>- Méthodes de résolution des problèmes NP-Complets.</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
      <ref-intervenant ref="IN7001"/>
      <ref-intervenant ref="IN13794"/>
   </ue>
   <ue id="ENSINAU3">
      <nom>Réseaux</nom>
      <credit>6</credit>
      <vol_horaire>60</vol_horaire>
      <description>
         <p>
            <t>- Architecture en couches, standard OSI</t>
            <br/>
            <t>- Couche physique</t>
            <br/>
            <t>- Couche liaison de Données</t>
            <br/>
            <t>- Réseau IP</t>
            <br/>
            <t>- Algorithmes de routage, routage IP</t>
            <br/>
            <t>- Protocole TCP/IP</t>
            <br/>
            <t>- Couche Application : HTTP, SMTP, FTP, ...</t>
            <br/>
            <t>- Bases des protocoles cryptographiques (terminologie, architecture à clef publique).</t>
            <br/>
            <t>- Introduction à la Sécurité des réseaux.</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINAU4">
      <nom>Programmation fonctionnelle</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>1- Introduction à la programmation fonctionnelle, sur l'exemple du langage</t>
            <br/>
            <t>OCaml</t>
            <br/>
            <t>Expressions, évaluation, types de base. Polymorphisme, ordre supérieur.</t>
            <br/>
            <t>Fonctions récursives, filtrage. Les diverses stratégies d'évaluation, application à la programmation d'un opérateur de point fixe.</t>
            <br/>
            <t>2- Les types</t>
            <br/>
            <t>Sommes, types récursifs, polymorphes. Arbres. Filtrage.</t>
            <br/>
            <t>3- Sémantique opérationnelle</t>
            <br/>
            <t>Liaisons, environnements, clôtures. Évaluation des fonctions récursives .</t>
            <br/>
            <t>4- Aspects impératifs</t>
            <br/>
            <t>Exceptions, entrées-sorties, séquencement, fichiers, références, tableaux, enregistrements.</t>
            <br/>
            <t>5- Implantation du filtrage en OCaml</t>
            <br/>
            <t>Termes formels, substitutions, filtrage.</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINAU5">
      <nom>Programmation parallèle</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>Ma position est que dans programmation parallèle, on fait de la programmation multithread en JAVA, en tâchant d'être rigoureux : présentation des problèmes et des solutions algorithmiques ; classes utiles ; construction de classe threadsafe ; détail de modèle mémoire</t>
            <br/>
            <t>Java et garantie DRF.</t>
            <br/>
            <t>Cette année j'ai ajouté vérification formelle d'algorithmes parallèles (ou distribués).</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINAU6">
      <nom>Programmation logique</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>- Introduction. Forme générale des règles. Effacement, unification, backtracking. Contrôle de l'exécution.</t>
            <br/>
            <t>- Listes, arbres et n-uplets. Liste représentée par différence de listes. Ajout en tête et en queue, concaténation.</t>
            <br/>
            <t>- Analyseurs syntaxiques. Construction d'un arbre syntaxique. Liste des feuilles d'un arbre. Freeze et analyse par feuille.</t>
            <br/>
            <t>- Règles prédéfinies.</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINAU7">
      <nom>Outils de l'internet</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>- Présentation d'Internet.</t>
            <br/>
            <t>- Les langages et les normes sur Internet.</t>
            <br/>
            <t>- Les protocoles : HTTP, HTTP, SMTP, IMAP, POP3</t>
            <br/>
            <t>- Les applications web.</t>
            <br/>
            <t>- Sécurité.</t>
            <br/>
            <t>- Les nouvelles et futures technologies.</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINAU8">
      <nom>Système embarqué</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description/>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINAU9">
      <nom>Fondamentaux pour l'ingénierie des langues</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>- Rappel de théorie des langages</t>
            <br/>
            <t>- Algorithmes d'analyse syntaxique pour grammaires ambiguës</t>
            <br/>
            <t>- Transducteurs finis et leur application en TAL</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINBU1">
      <nom>Anglais</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>Un enseignement destiné à confirmer l'utilisation de l'anglais dans le contexte de l'informatique ainsi que dans la pratique professionnelle.</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINBU10">
      <nom>Intégration des systèmes d'information</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>- Problématique d'intégration des SI</t>
            <br/>
            <t>- Architectures et patrons d'intégration</t>
            <br/>
            <t>- Systèmes d'Information d'entreprises</t>
            <br/>
            <t>- Systèmes d'Information sur Internet</t>
         </p>
      </description>
      <plan>Plan ?</plan>
      <lieu>Luminy</lieu>
   </ue>
   <ue id="ENSINBU11">
      <nom>Initiation à la fouille de données et à l’optimisation des SGBD</nom>
      <credit>3</credit>
      <vol_horaire>30</vol_horaire>
      <description>
         <p>
            <t>Actuellement, de plus en plus de données sont conservées sans être réellement exploitées. Elles représentent pourtant une source importante d’information. La fouille de données peut-être définie comme le processus permettant d’extraire de l’information non triviale et non préalablement connue à partir des données. Dans cet enseignement, nous nous focaliserons sur l’extraction de corrélations entre les données (règle d’association, Dépendances Fonctionnelles...) et nous verrons des techniques de mesure de la qualité des données (détection et correction d’erreur).</t>
            <br/>
